# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/custom_list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_custom_list_item(object):
    def setupUi(self, custom_list_item):
        custom_list_item.setObjectName("custom_list_item")
        custom_list_item.resize(1037, 41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(custom_list_item.sizePolicy().hasHeightForWidth())
        custom_list_item.setSizePolicy(sizePolicy)
        custom_list_item.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(custom_list_item)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.check_button = QtWidgets.QPushButton(custom_list_item)
        self.check_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/unchecked.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_button.setIcon(icon)
        self.check_button.setCheckable(True)
        self.check_button.setObjectName("check_button")
        self.horizontalLayout_3.addWidget(self.check_button)
        self.task_field = QtWidgets.QLabel(custom_list_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.task_field.sizePolicy().hasHeightForWidth())
        self.task_field.setSizePolicy(sizePolicy)
        self.task_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.task_field.setScaledContents(True)
        self.task_field.setWordWrap(True)
        self.task_field.setObjectName("task_field")
        self.horizontalLayout_3.addWidget(self.task_field)
        self.trash_button = QtWidgets.QPushButton(custom_list_item)
        self.trash_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/trashcan.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trash_button.setIcon(icon1)
        self.trash_button.setObjectName("trash_button")
        self.horizontalLayout_3.addWidget(self.trash_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(custom_list_item)
        QtCore.QMetaObject.connectSlotsByName(custom_list_item)

    def retranslateUi(self, custom_list_item):
        _translate = QtCore.QCoreApplication.translate
        custom_list_item.setWindowTitle(_translate("custom_list_item", "Form"))
        self.task_field.setText(_translate("custom_list_item", "TextLabel"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    custom_list_item = QtWidgets.QWidget()
    ui = Ui_custom_list_item()
    ui.setupUi(custom_list_item)
    custom_list_item.show()
    sys.exit(app.exec_())
