# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_timer_widget(object):
    def setupUi(self, timer_widget):
        timer_widget.setObjectName("timer_widget")
        timer_widget.resize(594, 0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(timer_widget.sizePolicy().hasHeightForWidth())
        timer_widget.setSizePolicy(sizePolicy)
        timer_widget.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(timer_widget)
        self.verticalLayout_2.setContentsMargins(35, 35, 35, 35)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(timer_widget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.countdown_circle = QtWidgets.QLabel(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countdown_circle.sizePolicy().hasHeightForWidth())
        self.countdown_circle.setSizePolicy(sizePolicy)
        self.countdown_circle.setMinimumSize(QtCore.QSize(250, 250))
        self.countdown_circle.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.countdown_circle.setFont(font)
        self.countdown_circle.setStyleSheet("")
        self.countdown_circle.setAlignment(QtCore.Qt.AlignCenter)
        self.countdown_circle.setObjectName("countdown_circle")
        self.verticalLayout.addWidget(self.countdown_circle, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.set_timer_duration_bar = QtWidgets.QSlider(self.main_frame)
        self.set_timer_duration_bar.setMinimumSize(QtCore.QSize(300, 0))
        self.set_timer_duration_bar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.set_timer_duration_bar.setMaximum(10800)
        self.set_timer_duration_bar.setSingleStep(60)
        self.set_timer_duration_bar.setOrientation(QtCore.Qt.Horizontal)
        self.set_timer_duration_bar.setObjectName("set_timer_duration_bar")
        self.verticalLayout.addWidget(self.set_timer_duration_bar, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stop_timer_button = QtWidgets.QPushButton(self.main_frame)
        self.stop_timer_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_timer_button.sizePolicy().hasHeightForWidth())
        self.stop_timer_button.setSizePolicy(sizePolicy)
        self.stop_timer_button.setMinimumSize(QtCore.QSize(150, 30))
        self.stop_timer_button.setMaximumSize(QtCore.QSize(150, 35))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_timer_button.setIcon(icon)
        self.stop_timer_button.setObjectName("stop_timer_button")
        self.horizontalLayout.addWidget(self.stop_timer_button, 0, QtCore.Qt.AlignVCenter)
        self.start_stop_timer_button = QtWidgets.QPushButton(self.main_frame)
        self.start_stop_timer_button.setMinimumSize(QtCore.QSize(150, 30))
        self.start_stop_timer_button.setMaximumSize(QtCore.QSize(150, 35))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_stop_timer_button.setIcon(icon1)
        self.start_stop_timer_button.setObjectName("start_stop_timer_button")
        self.horizontalLayout.addWidget(self.start_stop_timer_button, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.main_frame)

        self.retranslateUi(timer_widget)
        QtCore.QMetaObject.connectSlotsByName(timer_widget)

    def retranslateUi(self, timer_widget):
        _translate = QtCore.QCoreApplication.translate
        timer_widget.setWindowTitle(_translate("timer_widget", "Form"))
        self.countdown_circle.setText(_translate("timer_widget", "00:00:00"))
        self.stop_timer_button.setText(_translate("timer_widget", "Stop and reset"))
        self.start_stop_timer_button.setText(_translate("timer_widget", "Start"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    timer_widget = QtWidgets.QWidget()
    ui = Ui_timer_widget()
    ui.setupUi(timer_widget)
    timer_widget.show()
    sys.exit(app.exec_())
